stages:
  - name: rivet
    dependencies: ['init']
    scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
        outputjson: '{workdir}/output.json'
        hepmc: {step: init, output: hepmc}
        analysis: {step: init, output: analysis}
      step: {$ref: 'step.yml'}
