stages:
  - name: madgraph_pythia
    dependencies: ['init']
    scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
        outputhepmc: '{workdir}/output.hepmc'
        n_events: {step: init, output: n_events}
        param_card: {step: init, output: param_card}
        run_card: {step: init, output: run_card}
        proc_card: {step: init, output: proc_card}
        ufotar: {step: init, output: ufotar}
      step: {$ref: 'step.yml'}
